package com.hsjry.cc.batch.spring.dao.mapper;

import com.hsjry.cc.batch.spring.dao.model.PublicCcSmsSign;
import com.hsjry.cc.batch.spring.dao.model.PublicCcSmsSignExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PublicCcSmsSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    long countByExample(PublicCcSmsSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int deleteByExample(PublicCcSmsSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int deleteByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int insert(PublicCcSmsSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int insertSelective(PublicCcSmsSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    List<PublicCcSmsSign> selectByExample(PublicCcSmsSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    PublicCcSmsSign selectByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") PublicCcSmsSign record, @Param("example") PublicCcSmsSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int updateByExample(@Param("record") PublicCcSmsSign record, @Param("example") PublicCcSmsSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int updateByPrimaryKeySelective(PublicCcSmsSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_cc_sms_sign
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    int updateByPrimaryKey(PublicCcSmsSign record);
}