package com.batch.dao.model;

import java.util.Date;

public class MyModel {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_cc_sms_sign.sign_id
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    private Integer signId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_cc_sms_sign.sign_code
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    private String signCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_cc_sms_sign.sign_content
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    private String signContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_cc_sms_sign.create_time
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_cc_sms_sign.update_time
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_cc_sms_sign.create_by
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_cc_sms_sign.update_by
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_cc_sms_sign.sign_id
     *
     * @return the value of public_cc_sms_sign.sign_id
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public Integer getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_cc_sms_sign.sign_id
     *
     * @param signId the value for public_cc_sms_sign.sign_id
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public void setSignId(Integer signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_cc_sms_sign.sign_code
     *
     * @return the value of public_cc_sms_sign.sign_code
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public String getSignCode() {
        return signCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_cc_sms_sign.sign_code
     *
     * @param signCode the value for public_cc_sms_sign.sign_code
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public void setSignCode(String signCode) {
        this.signCode = signCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_cc_sms_sign.sign_content
     *
     * @return the value of public_cc_sms_sign.sign_content
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public String getSignContent() {
        return signContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_cc_sms_sign.sign_content
     *
     * @param signContent the value for public_cc_sms_sign.sign_content
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public void setSignContent(String signContent) {
        this.signContent = signContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_cc_sms_sign.create_time
     *
     * @return the value of public_cc_sms_sign.create_time
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_cc_sms_sign.create_time
     *
     * @param createTime the value for public_cc_sms_sign.create_time
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_cc_sms_sign.update_time
     *
     * @return the value of public_cc_sms_sign.update_time
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_cc_sms_sign.update_time
     *
     * @param updateTime the value for public_cc_sms_sign.update_time
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_cc_sms_sign.create_by
     *
     * @return the value of public_cc_sms_sign.create_by
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_cc_sms_sign.create_by
     *
     * @param createBy the value for public_cc_sms_sign.create_by
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_cc_sms_sign.update_by
     *
     * @return the value of public_cc_sms_sign.update_by
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_cc_sms_sign.update_by
     *
     * @param updateBy the value for public_cc_sms_sign.update_by
     *
     * @mbg.generated Mon Aug 27 08:51:14 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}